import Header from "@/components/Header";
import RightSidebar from "@/components/RightSidebar";
import AppProvider from "@/providers/AppProvider";
import { Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      style={{
        backgroundColor: "black",
      }}
    >
      <body
        className={`${comfortaa.className} antialiased`}
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          backgroundColor: "black",
        }}
      >
        <Suspense>
          <AppProvider>
            <Header />
            <Flex
              padding={"24px"}
              marginRight={"324px"}
              lgDown={{
                marginRight: "0px",
              }}
              position={"relative"}
              top={"52px"}
            >
              {children}
              <RightSidebar />
            </Flex>
          </AppProvider>
        </Suspense>
      </body>
    </html>
  );
}
